### ISSUE TITLE
Clearer step-wise UI workflow for setting up a new topic

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/impact-visualizer#11]
For the Management Actions component, for initial setup of a new topic, the UI should clearly direct the user through each of the necessary steps of adding articles, adding users, and generating the data. At least for a topic that hasn't yet gone through all three steps, I think it should only show one of these at a time, at the top of the Management Actions, so that it's very clear what they should do next to move forward.

I also think we ought to automatically import users and articles at the time of CSV upload, combing upload and import into a single action.

The current UI is okay for after timepoint generation has been kicked off.

**Comment by ragesoss** [comment]
@mattfordham if you can squeeze this in before Wikimania (first week of August) that would be ideal.

**Comment by mattfordham** [comment]
@ragesoss How would you prioritize against the new server setup?

**Comment by ragesoss** [comment]
@mattfordham after.

**Comment by ragesoss** [comment]
This is in decent shape now.
