### ISSUE TITLE
Error in Vite build during capistrano deployment

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/impact-visualizer#4]
I attempted to deploy to production, but I'm getting an unfamiliar error:

```
rake stdout: Building with Vite ⚡️
Internal Error: impact-visualizer@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at V0.getCandidates (/home/deploy/.yarn/releases/yarn-3.6.3.cjs:435:5145)
    at kf.getCandidates (/home/deploy/.yarn/releases/yarn-3.6.3.cjs:391:1264)
    at /home/deploy/.yarn/releases/yarn-3.6.3.cjs:439:8033
    at df (/home/deploy/.yarn/releases/yarn-3.6.3.cjs:390:11070)
    at ge (/home/deploy/.yarn/releases/yarn-3.6.3.cjs:439:8013)
    at async Promise.allSettled (index 0)
    at async io (/home/deploy/.yarn/releases/yarn-3.6.3.cjs:390:10398)
    at async /home/deploy/.yarn/releases/yarn-3.6.3.cjs:439:8545
    at async ti.startProgressPromise (/home/deploy/.yarn/releases/yarn-3.6.3.cjs:390:47579)
    at async je.resolveEverything (/home/deploy/.yarn/releases/yarn-3.6.3.cjs:439:6573)

```

@mattfordham any ideas?

**Comment by mattfordham** [comment]
@ragesoss Have you previously deployed successfully? Or is this the first time?

**Comment by ragesoss** [comment]
@mattfordham first time

**Comment by mattfordham** [comment]
@ragesoss Ok, I'll take a closer look and will see what I can figure out. How pressing is this?

**Comment by ragesoss** [comment]
@mattfordham not urgent, but I'm eager to put the new feature I merged from @Aminehassou through its paces.

**Comment by mattfordham** [comment]
@ragesoss Got it. Will attempt to investigate today!

**Comment by mattfordham** [comment]
@ragesoss Did you run both `yarn install` and `bundle install` first?

**Comment by mattfordham** [comment]
@ragesoss The asset precompile stuff ran as expected locally for me AND when running manually on the server. That said, it failed within the context of `cap production deploy` for me too. No solution was immediately obvious. I'll have to return to poke again later today or tomorrow as I have time.

**Comment by mattfordham** [comment]
@ragesoss After another poke, I realized my local Yarn and what is on the server were not the same version. I added some config to the project to ensure the same version in both places and this seemed to do the trick. I was able to run a full deploy successfully.

**Comment by ragesoss** [comment]
Sweet, thanks!
